const EDITOR_ZOOMS=[0.25,0.5,1,2,3,4,6,8];
let editorZoom=1;
function editorRenderScale(){return C(Math.floor(4096/Math.max(aw(),ah())),4,30)}
function applyEditorScale(){let c=$('editor'),cssCell=30*editorZoom;c.style.width=(aw()*cssCell)+'px';c.style.height=(ah()*cssCell)+'px';$('editorZoom').textContent=Math.round(editorZoom*100)+'%'}
function changeEditorZoom(delta){let i=EDITOR_ZOOMS.indexOf(editorZoom);if(i<0)i=2;i=C(i+delta,0,EDITOR_ZOOMS.length-1);editorZoom=EDITOR_ZOOMS[i];applyEditorScale();setStatus('Editor zoom '+Math.round(editorZoom*100)+'%')}
function artColor(x,y){let color=null;for(let s of fr().sprites){if(!s.visible)continue;let lx=x-s.ox,ly=y-s.oy;if(lx<0||ly<0||lx>=sz()||ly>=sz()||!s.mask[ly][lx])continue;let a=s.lines[ly];if(!a.color)continue;if(a.cc){if(color!==null)color=(color|a.color)&15}else if(color===null)color=a.color}return color}
function drawEditor(){let c=$('editor'),g=c.getContext('2d'),w=aw(),h=ah();editorCell=editorRenderScale();c.width=w*editorCell;c.height=h*editorCell;for(let y=0;y<h;y++)for(let x=0;x<w;x++){g.fillStyle=(x+y)%2?'#171b22':'#20252d';g.fillRect(x*editorCell,y*editorCell,editorCell,editorCell);let col=artColor(x,y);if(col!==null){g.fillStyle=PAL[col];g.fillRect(x*editorCell+1,y*editorCell+1,editorCell-2,editorCell-2)}}g.strokeStyle='rgba(255,255,255,.09)';g.lineWidth=1;for(let x=0;x<=w;x++){g.beginPath();g.moveTo(x*editorCell+.5,0);g.lineTo(x*editorCell+.5,c.height);g.stroke()}for(let y=0;y<=h;y++){g.beginPath();g.moveTo(0,y*editorCell+.5);g.lineTo(c.width,y*editorCell+.5);g.stroke()}let s=layer();g.strokeStyle='#65d7c0';g.lineWidth=2;g.strokeRect(s.ox*editorCell+1,s.oy*editorCell+1,sz()*editorCell-2,sz()*editorCell-2);let lineY=(s.oy+L)*editorCell;g.strokeStyle='rgba(101,215,192,.65)';g.lineWidth=1;g.strokeRect(s.ox*editorCell+2,lineY+2,sz()*editorCell-4,editorCell-4);applyEditorScale()}
function editorPoint(e){let r=$('editor').getBoundingClientRect();return{x:C(Math.floor((e.clientX-r.left)/r.width*aw()),0,aw()-1),y:C(Math.floor((e.clientY-r.top)/r.height*ah()),0,ah()-1)}}
function layerPoint(p){return{x:p.x-layer().ox,y:p.y-layer().oy}}
function inLayer(p){return p.x>=0&&p.y>=0&&p.x<sz()&&p.y<sz()}
function put(a,b,v){let la=layerPoint(a),lb=layerPoint(b);if(!inLayer(la)&&!inLayer(lb)){setStatus('Outside selected layer');return}let x0=la.x,y0=la.y,x1=lb.x,y1=lb.y,dx=Math.abs(x1-x0),sx=x0<x1?1:-1,dy=-Math.abs(y1-y0),sy=y0<y1?1:-1,er=dx+dy;for(;;){if(x0>=0&&y0>=0&&x0<sz()&&y0<sz())layer().mask[y0][x0]=v;if(x0===x1&&y0===y1)break;let e2=2*er;if(e2>=dy){er+=dy;x0+=sx}if(e2<=dx){er+=dx;y0+=sy}}dirty()}
function toolset(t){tool=t;$('pencil').classList.toggle('on',t==='pencil');$('eraser').classList.toggle('on',t==='eraser')}
let ed=$('editor');ed.oncontextmenu=e=>e.preventDefault();ed.addEventListener('pointerdown',e=>{if(e.pointerType==='mouse'&&e.button!==0&&e.button!==2)return;e.preventDefault();drag=true;let p=editorPoint(e),lp=layerPoint(p);last=p;if(inLayer(lp))L=lp.y;put(p,p,e.button===2||tool==='eraser'?0:1);ed.setPointerCapture?.(e.pointerId);render()});ed.addEventListener('pointermove',e=>{if(!drag)return;e.preventDefault();let p=editorPoint(e),lp=layerPoint(p);put(last,p,tool==='eraser'||(e.pointerType==='mouse'&&(e.buttons&2))?0:1);last=p;if(inLayer(lp))L=lp.y;render()});['pointerup','pointercancel','lostpointercapture'].forEach(ev=>ed.addEventListener(ev,()=>{drag=false;last=null}));

function shiftBitmap(dx,dy){let n=sz(),m=mask();for(let y=0;y<n;y++)for(let x=0;x<n;x++)m[(y+dy+n)%n][(x+dx+n)%n]=layer().mask[y][x];layer().mask=m;dirty();render()}
function flip(h){let n=sz(),m=mask();for(let y=0;y<n;y++)for(let x=0;x<n;x++)m[h?y:n-1-y][h?n-1-x:x]=layer().mask[y][x];layer().mask=m;dirty();render()}
function moveLayer(dx,dy){layer().ox+=dx;layer().oy+=dy;dirty();render()}

function sx(s){return P.sceneX+s.ox}
function sy(s){return P.sceneY+s.oy}
function covers(s,y){return s.visible&&y>=sy(s)&&y<sy(s)+sz()*mg()}
function drawScene(showSelection=true){let c=$('screenCanvas'),g=c.getContext('2d'),arr=fr().sprites;g.fillStyle='#101018';g.fillRect(0,0,256,212);for(let y=0;y<212;y++){let cand=arr.filter(s=>covers(s,y));if($('limit').checked)cand=cand.slice(0,8);let cols=Array(256).fill(null);for(let s of cand){let py=C(Math.floor((y-sy(s))/mg()),0,sz()-1),a=s.lines[py],base=sx(s)+(a.ec?-32:0);for(let x=0;x<256;x++){let px=Math.floor((x-base)/mg());if(px<0||px>=sz()||!s.mask[py][px]||!a.color)continue;if(a.cc){if(cols[x]!==null)cols[x]=(cols[x]|a.color)&15}else if(cols[x]===null)cols[x]=a.color}}for(let x=0;x<256;x++)if(cols[x]!==null){g.fillStyle=PAL[cols[x]];g.fillRect(x,y,1,1)}}if(showSelection){let s=layer();g.strokeStyle='rgba(255,255,255,.7)';g.strokeRect(sx(s)+.5,sy(s)+.5,sz()*mg(),sz()*mg());g.strokeStyle='rgba(101,215,192,.5)';g.strokeRect(P.sceneX+.5,P.sceneY+.5,aw(),ah())}}
function applyPreviewScale(){let c=$('screenCanvas');c.style.width=(256*previewScale)+'px';c.style.height=(212*previewScale)+'px';$('previewZoom').textContent=previewScale+'×'}
function changePreviewScale(delta){previewScale=Math.max(1,previewScale+delta);applyPreviewScale();setStatus('Preview '+previewScale+'×')}
function savePreviewImage(){drawScene(false);let src=$('screenCanvas'),out=document.createElement('canvas'),scale=previewScale;out.width=src.width*scale;out.height=src.height*scale;let g=out.getContext('2d');g.imageSmoothingEnabled=false;g.drawImage(src,0,0,out.width,out.height);out.toBlob(blob=>{if(blob)dl(blob,'pixlverse-screen'+P.screen+'-'+scale+'x.png','image/png');drawScene(true)},'image/png')}
function loadGraph(){let c=$('loadCanvas'),g=c.getContext('2d'),mx=0,over=0;g.fillStyle='#10141b';g.fillRect(0,0,180,212);for(let y=0;y<212;y++){let n=fr().sprites.filter(s=>covers(s,y)).length;mx=Math.max(mx,n);if(n>8)over++;g.fillStyle=n>8?'#f3c96b':'#65d7c0';g.fillRect(0,y,Math.min(170,n*16),1)}$('loadInfo').textContent='peak '+mx+'/8\n'+over+' overloaded lines'}
function warnings(){let bad=0;for(let y=0;y<212;y++)if(fr().sprites.filter(s=>covers(s,y)).length>8)bad++;let outside=fr().sprites.filter(s=>s.ox<0||s.oy<0||s.ox+sz()>aw()||s.oy+sz()>ah()).length;let a=[];if(bad)a.push('⚠ '+bad+' scanlines exceed 8 sprites');if(outside)a.push(outside+' layer(s) extend outside canvas');$('warn').textContent=a.join(' · ')}

function dl(data,name,type='application/octet-stream'){let a=document.createElement('a'),b=data instanceof Blob?data:new Blob([data],{type});a.href=URL.createObjectURL(b);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
function patBytes(){let out=new Uint8Array(2048);for(let s of fr().sprites){let p=sz()===16?(s.pattern&252):s.pattern;if(sz()===8){for(let y=0;y<8;y++){let b=0;for(let x=0;x<8;x++)b|=s.mask[y][x]<<(7-x);out[p*8+y]=b}}else{let q=[[0,0],[0,8],[8,0],[8,8]];q.forEach(([ox,oy],qi)=>{for(let y=0;y<8;y++){let b=0;for(let x=0;x<8;x++)b|=s.mask[oy+y][ox+x]<<(7-x);out[(p+qi)*8+y]=b}})}}return out}
function colBytes(){let o=new Uint8Array(512);fr().sprites.slice(0,32).forEach((s,i)=>{for(let y=0;y<16;y++){let a=s.lines[y],b=a.color&15;if(a.ec)b|=128;if(a.cc)b|=64;if(a.ic)b|=32;o[i*16+y]=b}});return o}
function satBytes(){let o=new Uint8Array(128);fr().sprites.slice(0,32).forEach((s,i)=>{o[i*4]=(sy(s)-1)&255;o[i*4+1]=sx(s)&255;o[i*4+2]=sz()===16?(s.pattern&252):(s.pattern&255);o[i*4+3]=0});for(let i=fr().sprites.length;i<32;i++)o[i*4]=216;return o}
